image: node:slim

stages:          # List of stages for jobs, and their order of execution
  - build
  - test
  - deploy

cache:
  paths:
    - node_modules/

before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD registry.gitlab.envent.ru

build-job:       
  stage: build
  tags:
    - docker
  script:
    - npm install
    - echo "Compiling the code..."
    - echo "Compile complete."


deploy-job:      # This job runs in the deploy stage.
  stage: deploy  # It only runs when *both* jobs in the test stage complete successfully.
  script:
    - echo "Deploying application..."
    - echo "Application successfully deployed."
