all:
    hosts:
        instanse-2: 
            ansible_host: 35.217.43.20
        instanse-1: 
            ansible_host: 34.116.151.168
            ansible_ssh: 2222
        instanse-3: 
            ansible_host: 34.118.65.218

        