---
- hosts: all
  ##hosts: [zabbix_agent]
  gather_facts: false
  remote_user: root
  become: true
  vars_files:
    - vars/vars.yml

  tasks:
      - name: "check if ssh is running on"
        delegate_to: localhost
        wait_for:
        port: "{{ desired_port }}"
        host: "{{ ansible_host }}"
        timeout: 10
        ignore_errors: true
        register: desired_port_check

      

      - name: gather os specific variables
        include_vars: "{{ item }}"
        with_first_found:
            - "vars/{{ ansible_distribution }}.yaml"

      - name: Download zabbix repo package
        get_url:
            url: "{{ zabbix_repo_url }}"
            dest: /tmp/zabbix.deb

      - name: Install zabbix repo
        become: yes
        apt:
            deb: /tmp/zabbix.deb
            state: present

      - name: Install zabbix agent
        become: yes
        apt:
            name: zabbix-agent
            state: present
            update_cache: yes

      - name: Stop service zabbix-agent
        become: yes
        service:
            name: zabbix-agent
            state: stopped

      - name: Remove zabbix config file
        become: yes
        file:
            path: /etc/zabbix/zabbix_agentd.conf
            state: absent

      - name: Create new zabbix config file from template
        become: yes
        template:
            src: "templates/zabbix_agentd.conf.j2"
            dest: "/etc/zabbix/zabbix_agentd.conf"

      - name: Start service zabbix-agent
        become: yes
        service:
            name: zabbix-agent
            state: started