---
- name: Install python in target node with ansible
  hosts: all
  remote_user: root
  #sudo: yes
  become: true
  gather_facts: no
  tasks:
  - name: Copy script to remote_machine
    template: src=script.sh dest=/tmp/script.sh mode=0755
  - name: install python
    command: bash /tmp/script.sh
  