---
- hosts: all
  become: yes

  vars_files:
    - vars.yml

  tasks:
   - name: "Create schema in db"
     become_user: postgres
     community.postgresql.postgresql_schema:
        db: "{{ db_name }}"
        port: "{{ pg_port }}"
        name: "{{ db_schema }}"
