---
- name: Create db
  hosts: all
  become: true
  gather_facts: no
  
  vars_files:
    - vars.yml

  tasks:
   - name: Copy script to remote_host
     remote_user: root
     template: 
      src: create_table.sql 
      dest: /tmp/create_table.sql 
      mode: 0755

   - name: Add some data to our database
     #port: "{{ pg_port }}"
     #port: 5433
     become_user: postgres
     shell: psql {{ db_name }} < /tmp/create_table.sql