- hosts: all
  become: yes

  vars_files:
    - vars.yml

  tasks:
   - name: "Delete table in db"
     become_user: postgres
     community.postgresql.postgresql_table:
        db: "{{ db_name }}"
        port: "{{ pg_port }}"
        #name: "{{ table_name }}"
        name: LOCAL.AIRFLOW_DAGS
        state: absent