---
- hosts: all
  become: yes

  vars_files:
    - vars.yml

  pre_tasks:
    - name: "Install packages"
      apt: "name={{ item }} state=present"
      with_items:
        - postgresql
        - postgresql-contrib
        - python3-psycopg2

    - name: Create the database specified in vars
      become: true
      become_user: postgres
      postgresql_db: 
          name={{ db_name }}
          template='template0'
          state=present

    - name: "Ensure the PostgreSQL service is running"
      service: "name={{ item }} state=started enabled=yes"
      with_items:
        - postgresql


    - name: "Ensure user has access to the database"
      become_user: postgres
      postgresql_user: 
          db={{ db_name }}
          name={{ db_user }}
          password={{ db_password }}
          priv=ALL
          state=present

    - name: "Ensure user does not have unnecessary privileges"
      become_user: postgres
      postgresql_user: 
          name={{ db_user }}
          role_attr_flags=NOSUPERUSER,NOCREATEDB
          state=present

    - name: "Set port parameter"
      become_user: postgres
      community.postgresql.postgresql_set:
        name: port
        value: "{{ pg_port }}"
      register: set
      notify: restart postgres          

  handlers:
    - name: restart postgres
      #debug: msg="Restart PostgesSQL"
      service: name=postgresql state=restarted   